logging.level.root=info
logging.level.org.apache=info
invoice.folder.templates=./templates
invoice.folder.data=./data
invoice.export.url=http://192.168.10.222:8080
server.port=8080
server.servlet.context-path=/api
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.servlet.multipart.max-file-size=10MB
spring.web.cors.allowed-origins=http://192.168.10.85:33005