spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.servlet.multipart.max-file-size=10MB
spring.web.cors.allowed-origins=http://192.168.10.85:33005,http://10.14.52.14:8080
server.port=8082
logging.level.root=info
invoice.folder.templates=/finance/templates
invoice.folder.data=/finance/data
invoice.export.url=http://10.14.52.14:8080