spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.servlet.multipart.max-file-size=10MB
server.port=8082
logging.level.root=info
invoice.folder.templates=./templates
invoice.folder.data=./data
invoice.export.url=http://192.168.10.101:8080